apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask-metrics'
        static_configs:
          - targets: ['flask-app-service:5000']  # Replace with your Flask app's service name and port

