apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: yourdockerhubusername/myflaskapp:v1
        ports:
        - containerPort: 5000
        env:
        - name: USERNAME
          value: "DefaultUser"
