apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-svc
  namespace: default
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: myflaskapp
  type: NodePort
